name: Docker Image CI

on:
  push:
    branches: [ main ]
    
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.DOCKER_REPOSITORY_NAME }}
  TAG: 0.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker test
      run: |
        docker build -t $DOCKER_USER/test -f Dockerfile.test .
        docker run --rm $DOCKER_USER/test
        docker rmi $DOCKER_USER/test
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: |
        docker build -t $DOCKER_USER/$REPO_NAME:$TAG .
    - name: docker push
      run: |
        docker push $DOCKER_USER/$REPO_NAME:$TAG
